/* bin2c — tiny build-time helper turning an arbitrary binary file into a C
 * source file defining `const unsigned char <name>[]` + `const size_t
 * <name>_len`, written to stdout. Used by icecreme/Makefile's embedded_
 * compiler_run.c/embedded_repl.c rules to bundle the precompiled self-
 * hosted-compiler driver and REPL bytecode directly into libcreme.a — see
 * that Makefile's own comment and embed.c's header comment. Deliberately
 * a standalone host-side tool (compiled with the plain host $(CC), never
 * cross-compiled, never linked into icecreme/libcreme.a itself) with no
 * dependency beyond libc, run once per build to generate a source file,
 * not part of the runtime at all.
 *
 * Usage: bin2c <input-file> <c-identifier> > <output.c> */
#include <stdio.h>
#include <stdlib.h>

int main(int argc, char **argv) {
  if (argc != 3) {
    fprintf(stderr, "usage: %s <input-file> <c-identifier>\n", argv[0]);
    return 1;
  }
  const char *path = argv[1];
  const char *name = argv[2];

  FILE *f = fopen(path, "rb");
  if (!f) {
    fprintf(stderr, "bin2c: %s: %s\n", path, "cannot open input file");
    return 1;
  }

  printf("/* Generated by icecreme/tools/bin2c.c from %s — do not edit. */\n", path);
  printf("#include <stddef.h>\n\n");
  printf("const unsigned char %s[] = {\n", name);

  size_t total = 0;
  int byte, col = 0;
  while ((byte = fgetc(f)) != EOF) {
    printf("0x%02x,", byte);
    total++;
    col++;
    if (col == 16) {
      printf("\n");
      col = 0;
    }
  }
  if (col != 0) printf("\n");
  fclose(f);

  /* A zero-length input would produce an illegal empty initializer list --
     not expected in practice (both current callers feed a real compiled
     .ice file), but pad with one harmless sentinel byte rather than
     emitting invalid C if it ever happens. */
  if (total == 0) printf("0x00,\n");

  printf("};\n");
  printf("const size_t %s_len = %zu;\n", name, total);
  return 0;
}
