require "./creme/errors"
require "./creme/value/values"
require "./creme/value/box"
require "./creme/compile/ast"
require "./creme/compile/opcode"
require "./creme/compile/chunk"
require "./creme/compile/bytecode_closure"
require "./creme/compile/bytecode_compiler"
require "./creme/compile/disassembler"
require "./creme/compile/icecreme_emitter"
require "./creme/value/rational"
require "./creme/value/complex"
require "./creme/read/lexer"
require "./creme/read/reader"
require "./creme/env"
require "./creme/compile/chunk_serializer"
require "./creme/compile/chunk_deserializer"
require "./creme/helpers"
require "./creme/eval/object_pool"
require "./creme/eval/builtin_helpers"
require "./creme/eval/interpreter"
require "./creme/eval/builtin_registration"
require "./creme/compile/analyzer"
require "./creme/eval/vm"
require "./creme/eval/record"
require "./creme/compile/syntax_rules"
require "./creme/eval/library"
require "./creme/eval/prelude"
require "./creme/eval/import"
require "./creme/modules/scheme/base"
require "./creme/modules/scheme/base/arithmetic"
require "./creme/modules/scheme/base/pairs_lists"
require "./creme/modules/scheme/base/vectors"
require "./creme/modules/scheme/base/higher_order"
require "./creme/modules/scheme/base/predicates"
require "./creme/modules/scheme/base/strings"
require "./creme/modules/scheme/base/io"
require "./creme/modules/scheme/base/misc"
require "./creme/modules/scheme/base/bytevectors"
require "./creme/modules/scheme/base/exceptions"
require "./creme/modules/scheme/base/write"
require "./creme/modules/scheme/char"
require "./creme/modules/scheme/inexact"
require "./creme/modules/scheme/cxr"
require "./creme/modules/scheme/lazy"
require "./creme/modules/scheme/read"
require "./creme/modules/scheme/eval"
require "./creme/modules/scheme/repl"
require "./creme/modules/scheme/r5rs"
require "./creme/modules/scheme/file"
require "./creme/modules/scheme/load"
require "./creme/modules/scheme/process_context"
require "./creme/modules/scheme/case_lambda"
require "./creme/modules/scheme/time"
require "./creme/modules/scheme/complex"
require "./creme/modules/creme/bootstrap"
require "./creme/modules/creme/big_decimal"
require "./creme/modules/creme/csv"
require "./creme/modules/creme/math"
require "./creme/modules/creme/regex"
require "./creme/modules/creme/ffi"
require "./creme/modules/creme/json"
require "./creme/modules/creme/yaml"
require "./creme/modules/creme/file"
require "./creme/modules/creme/time"
require "./creme/modules/creme/string"
require "./creme/modules/creme/format"
require "./creme/modules/creme/random"
require "./creme/modules/creme/digest"
require "./creme/modules/creme/secure_random"
require "./creme/modules/creme/cipher"
require "./creme/modules/creme/env"
require "./creme/modules/creme/process"
require "./creme/modules/creme/sql"
require "./creme/modules/creme/tui"
require "./creme/modules/creme/rfc8439"
require "./creme/modules/creme/http"
require "./creme/modules/creme/jose"
require "./creme/modules/creme/pkey"
require "./creme/modules/creme/x509"
require "./creme/modules/creme/mux"
require "./creme/modules/creme/hash_table"
require "./creme/modules/creme/treelist"
require "./creme/modules/creme/introspection"
require "./creme/modules/creme/term"
require "./creme/modules/creme/actor"
require "./creme/modules/creme/raft"
require "./creme/modules/creme/reader"
# prof_vm.cr (the (creme prof-vm) cooperative sampler) has no native/
# backtrace(3) dependency, so it's required unconditionally. prof_native.cr
# (the (creme prof-native) SIGPROF sampler) has no backtrace(3) on musl
# (Alpine) and fails to compile there — skip that one file on musl so creme
# still builds, just without that one library (and, transitively, without
# the (creme prof) frontend in modules/creme/prof.sld, which imports both).
require "./creme/modules/creme/prof_vm"
{% unless flag?(:musl) %}
  require "./creme/modules/creme/prof_native"
{% end %}
require "./creme/modules/scheme"
require "./creme/modules/creme"
# Defines `alias SchemeValue = <union of all concrete value types>`; required
# after every file that defines one of those types (order-independent for
# resolution, but kept here for clarity).
require "./creme/value/alias"
require "./creme/runner"
require "./creme/convert"

module Creme
  VERSION = "0.1.0"
end
